//! Lexicon (UI translations) and Prompts (AI instructions).

pub fn lexicon_fr() -> std::collections::HashMap<&'static str, &'static str> {
    let mut map = std::collections::HashMap::new();
    map.insert("frame_cible", " Configuration Globale (Moteur IA, Applications & Profils) ");
    map.insert("tab_config", " ⚙ Configuration Globale ");
    map.insert("tab_setup", " ⛭ Setup ");
    map.insert("tab_quickstart", " ❖ Aide - Démarrage Rapide ");
    map.insert("tab_prompts", " ✎ Éditeur de Prompts ");
    map.insert("tab_console", " ➤ Console & Supervision ");
    map.insert("tab_task_graph", " 🪵 Graphe de Tâches ");
    map.insert("frame_generateur", " ✨ Générateur de consigne rapide par l'IA ");
    map.insert("frame_timeline", " 🌐 Timeline Visuelle des Actions (Git Commit-Style) ");
    map.insert("frame_logs", " 🔴 Console d'Activité & Logs Temps Réel ");
    map.insert("lbl_langue", "Langue :");
    map.insert("lbl_profil", "Profil :");
    map.insert("lbl_selection_fenetres", "Fenêtres à suivre :");
    map.insert("lbl_context", "0. Contexte général de la situation :");
    map.insert("lbl_obj", "2. Condition d'arrêt (Do While / Limites) :");
    map.insert("lbl_tsk", "1. Tâche globale à accomplir (Consigne de départ) :");
    map.insert("lbl_dir", "3. Directives système spécifiques (Règles de l'IA) :");
    map.insert("lbl_moteur", "Moteur :");
    map.insert("lbl_url", "URL API :");
    map.insert("lbl_modele", "Modèle :");
    map.insert("chk_son", "🔔 Notification sonore");
    map.insert("chk_tooltips", "💬 Info-bulles actives");
    map.insert("btn_reinit", "🔄 Réinitialiser tout");
    map.insert("btn_sauver", "💾 Sauvegarder profil");
    map.insert("btn_opti_court", "🪄 Optimiser ce champ");
    map.insert("btn_clear_logs", "🗑️ Effacer les logs");
    map.insert("btn_copy_logs", "📋 Copier les Logs");
    map.insert("btn_copy_report", "📋 Copier le Rapport");
    map.insert("btn_generer_tout", "✨ Générer la configuration");
    map.insert("btn_lancer", "🚀 Lancer");
    map.insert("btn_arreter", "⏹️ Arrêter");
    map.insert("btn_resume", "▶️ Reprendre");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_stop_demande", "⏹️ Arrêt demandé par l'utilisateur.");
    map.insert("status_arrete", "⏹️ Arrêté.");
    map.insert("btn_pause", "⏸️ PAUSE");
    map.insert("btn_reprendre", "▶️ REPRENDRE L'AUTO");
    map.insert("btn_charger", "📂 Charger");
    map.insert("btn_sauver_profil", "💾 Sauver");
    map.insert("btn_supprimer", "🗑️ Suppr.");
    map.insert("statut_pret", "Statut : Prêt");
    map.insert("statut_pause", "Statut : En Pause");
    map.insert("statut_reprise", "💾 Une session précédente a été détectée. Prêt à reprendre !");
    map.insert("msg_reinit", "🔄 Tout a été réinitialisé à zéro !");
    map.insert("msg_sauve", "💾 Textes, langue et état sauvegardés !");
    map.insert("msg_vide", "⚠️ Écris d'abord ton besoin ou remplis le champ sélectionné !");
    map.insert("lbl_aucune_fenetre", "🖥️ Tout l'écran (aucune application cible spécifiée)");
    map.insert("msg_opti_en_cours", "🪄 Qwen optimise le champ sélectionné...");
    map.insert("msg_opti_ok", "✅ Champ optimisé par l'IA !");
    map.insert("msg_gen_en_cours", "⚡ Configuration de l'ensemble de l'orchestration par l'IA...");
    map.insert("msg_gen_ok", "✅ Tous les champs de prompt ont été structurés par l'IA !");
    map.insert("msg_confirm_titre", "Confirmation de sauvegarde");
    map.insert("msg_confirm_texte", "Attention : Voulez-vous sauvegarder les prompts et réglages actuels dans le profil '{}' ?");
    map.insert("msg_confirm_texte_generique", "Attention : Voulez-vous sauvegarder la configuration actuelle en tant que profil par défaut (save.enc) ?");
    map.insert("msg_nom_profil_titre", "Nouveau Profil");
    map.insert("msg_nom_profil_texte", "Saisissez le nom du nouveau profil de configuration :");
    map.insert("msg_nom_moteur_titre", "Nouveau Moteur IA");
    map.insert("msg_nom_moteur_texte", "Saisissez le nom du nouveau profil de moteur :");
    map.insert("msg_moteur_sauve", "✅ Moteur enregistré !");
    map.insert("msg_moteur_supprime", "🗑️ Moteur supprimé !");
    map.insert("msg_confirm_supp_moteur_titre", "Confirmer la suppression");
    map.insert("msg_confirm_supp_moteur_texte", "Voulez-vous vraiment supprimer définitivement le moteur '{}' ?");
    map.insert("msg_confirm_gen_titre", "Confirmer la génération globale");
    map.insert("msg_confirm_gen_texte", "Attention : La génération par l'IA va écraser l'ensemble de tes prompts actuels. Es-tu sûr de vouloir continuer ?");
    map.insert("msg_profil_sauve", "✅ Profil sauvegardé avec succès !");
    map.insert("msg_profil_charge", "📂 Profil chargé avec succès !");
    map.insert("msg_profil_supprime", "🗑️ Profil supprimé !");
    map.insert("msg_confirm_supp_titre", "Confirmer suppression");
    map.insert("msg_confirm_supp_texte", "Voulez-vous vraiment supprimer définitivement le profil '{}' ?");
    map.insert("btn_oui", "Oui");
    map.insert("btn_non", "Annuler");
    map.insert("legende_think", "T : Réflexion IA");
    map.insert("legende_wait", "W : App occupée");
    map.insert("legende_cool", "CD : Stabilisation");
    map.insert("legende_scroll", "S : Défiler");
    map.insert("legende_click", "C : Saisie");
    map.insert("legende_success", "★ : Succès");
    map.insert("legende_fail", "X : Échec");
    map.insert("legende_sleep", "SL : Veille/Verrou");
    map.insert("legende_static", "ST : Écran statique");
    map.insert("log_screen_asleep", "⏳ Écran en veille ou verrouillé. Attente de 5s...");
    map.insert("log_static_screen", "⏳ Écran statique détecté (aucun changement). Attente de 10s...");
    map.insert("status_screen_asleep", "⏳ Écran en veille ou verrouillé...");
    map.insert("status_static_screen", "⏳ Écran statique...");
    map.insert("all_screens", "TOUS LES ÉCRANS (Bureau virtuel)");
    map.insert("screen_title", "Bureau - Écran {}");
    map.insert("frame_ia", " 1. Fournisseur d'IA & Modèle (Vision LLM) ");
    map.insert("frame_windows", " 2. Applications cibles à surveiller ");
    map.insert("frame_profils", " 3. Gestion des Profils ");
    map.insert("tip_frame_ia", "Configure le fournisseur d'API d'IA locale ou distante ainsi que le modèle de vision à utiliser.");
    map.insert("tip_frame_windows", "Sélectionne et gère la liste des fenêtres à surveiller. Si vide, l'écran entier est surveillé.");
    map.insert("tip_frame_profils", "Charge, sauvegarde ou supprime des configurations complètes de prompts et de cibles.");
    map.insert("tip_context", "Contexte de départ pour guider la vision de l'IA (OS, outils, état de départ).");
    map.insert("tip_tsk", "Instructions d'action principales destinées à l'IA pour manipuler l'interface (en anglais technique).");
    map.insert("tip_obj", "Objectif final vérifiable visuellement pour que l'IA sache quand s'arrêter (en anglais technique).");
    map.insert("tip_dir", "Consignes de comportement et règles de sécurité strictes pour guider l'IA (en anglais technique).");
    map.insert("tip_refresh", "Rafraîchir la liste des fenêtres actives de votre bureau");
    map.insert("tip_add_win", "Ajouter l'application ciblée à la liste de surveillance");
    map.insert("tip_del_win", "Retirer l'application sélectionnée de la liste de surveillance");
    map.insert("tip_add_engine", "Ajouter un profil de fournisseur d'API d'IA (LM Studio, Ollama...)");
    map.insert("tip_del_engine", "Supprimer le profil d'IA actuellement affiché");
    map.insert("tip_load_profile", "Charger les prompts et la configuration de ce profil");
    map.insert("tip_save_profile", "Créer un nouveau profil ou écraser le profil existant");
    map.insert("tip_del_profile", "Supprimer définitivement ce profil de la mémoire");
    map.insert("tip_optimize_field", "Laisser l'IA locale reformuler et optimiser ce champ en anglais technique");
    map.insert("tip_generate_all", "Demander à l'IA de concevoir l'ensemble de l'automatisation à partir de ton idée");
    map.insert("tip_clear_memory", "Supprimer la mémoire du dernier travail en cours pour repartir à zéro");
    map.insert("log_fenetres_invisibles", "⏳ Aucune application surveillée n'est visible (minimisée ou fermée). Attente de 5s...");
    map.insert("status_fenetres_invisibles", "⏳ En attente des fenêtres cibles...");
    map.insert("log_detection_occupe", "⏳ Détection {} : OCCUPÉ. En attente...");
    map.insert("log_detection_libre", "⏳ Détection {} : LIBRE.");
    map.insert("log_fenetre_ajoutee", "➕ Fenêtre ajoutée à la surveillance : {}");
    map.insert("log_fenetre_retiree", "🗑️ Fenêtre retirée de la surveillance : {}");
    map.insert("log_ia_adapte", "⚙️ Paramètres IA adaptés pour {}.");
    map.insert("log_moteur_enregistre", "💾 Nouveau profil de moteur IA enregistré : {}");
    map.insert("log_impossible_suppr_dernier", "⚠️ Impossible de supprimer le dernier moteur restant.");
    map.insert("log_moteur_supprime", "🗑️ Moteur supprimé : {}");
    map.insert("log_profil_charge", "📂 Profil chargé : {}");
    map.insert("log_profil_supprime", "🗑️ Profil supprimé : {}");
    map.insert("log_champ_optimise", "🪄 IA : Champ '{}' optimisé.");
    map.insert("log_gen_demandee", "⚡ Génération automatique globale demandée...");
    map.insert("log_gen_injectee", "⚡ Configuration globale rédigée et injectée.");
    map.insert("log_lancement_moteur", "🚀 Lancement avec le moteur : {} ({})");
    map.insert("log_pause", "⏸️ Automate mis en pause.");
    map.insert("log_reprise", "▶️ Reprise de l'automate.");
    map.insert("log_reflexion_ia", "🧠 [RÉFLEXION IA] Capture et envoi pour analyse par {}...");
    map.insert("log_succes", "🏆 Fin de l'automatisation avec SUCCÈS !");
    map.insert("log_echec", "❌ Fin de l'automatisation avec ÉCHEC.");
    map.insert("log_attente_occupee", "⏳ [ATTENTE DE TÂCHE] L'application cible est occupée. Pause de {}s...");
    map.insert("log_lancement_visual", "📱 Lancement de l'Orchestrateur Visuel VibePilot.");
    map.insert("log_linux_detecte", "🐧 Système d'exploitation Linux détecté.");
    map.insert("log_warning_wayland", "⚠️ [WARNING WAYLAND] Session Wayland active. Veuillez utiliser X11 pour le bon fonctionnement des clics.");
    map.insert("log_x11_detecte", "✅ Serveur d'affichage X11 détecté. Prêt pour l'automatisation.");
    map.insert("log_sec_save", "[SECURITE] Configuration sauvegardée.");
    map.insert("log_error_opti", "❌ Erreur lors de l'optimisation : {}");
    map.insert("msg_attente_inactivite", "⏳ Attente inactivité ({}s)...");
    map.insert("status_reprise_init", "🔄 REPRISE...");
    map.insert("status_initialisation", "🚀 INITIALISATION...");
    map.insert("status_reflexion", "🧠 [RÉFLEXION IA] {} réfléchit...");
    map.insert("status_ia_decide", "🤖 IA : {}");
    map.insert("status_cooldown", "⏳ Cool-down ({}s)...");
    map.insert("status_waiting", "⏳ Waiting ({}s)...");
    map.insert("err_load_profile", "❌ Erreur de chargement du profil : {}");
    map.insert("err_generic", "❌ Erreur : {}");
    map.insert("log_memory_cleared", "🧹 Travail en cours/mémoire de reprise supprimé avec succès.");
    map.insert("log_reprise_existants", "💾 Reprise en cours : utilisation des prompts existants. Pour démarrer un nouvel objectif, cliquez d'abord sur 'Reset'.");
    map.insert("chk_theme_sombre", "🌙 Thème Sombre");
    map.insert("chk_auto_validate", "🔒 Auto-validation standard");
    map.insert("chk_auto_validate_dangerous", "🔒 Auto-validation commandes dangereuses");
    map.insert("tip_auto_validate", "Si activé, les actions de clic et défilement standard de l'IA sont exécutées sans confirmation.");
    map.insert("tip_auto_validate_dangerous", "Si activé, les commandes potentiellement dangereuses (ex: rm, format, sudo) sont validées automatiquement.");
    map.insert("tip_zoom_facteur", "Définit le niveau de zoom/mise à l'échelle de l'interface utilisateur. Utile si l'application apparaît trop petite ou trop grande sur votre écran.");
    map.insert("security_warning_titre", "⚠️ Actions de l'IA");
    map.insert("security_warning_texte", "L'IA a décidé des actions suivantes :\n\n{actions}\n\nVoulez-vous les exécuter ?");
    map.insert("security_warning_yes", "✅ Exécuter");
    map.insert("security_warning_no", "❌ Annuler");
    map.insert("btn_add_engine", "➕");
    map.insert("btn_del_engine", "🗑️");
    map.insert("btn_add_window", "➕");
    map.insert("btn_refresh_windows", "🔄");
    map.insert("lbl_auth_mode", "Authentification :");
    map.insert("lbl_api_key", "Clé API :");
    map.insert("lbl_auth_login", "Identifiant :");
    map.insert("lbl_auth_password", "Mot de passe :");
    map.insert("lbl_request_timeout", "Timeout Requête (sec) :");
    map.insert("lbl_auth_none", "Aucune");
    map.insert("lbl_auth_api_key", "Clé API");
    map.insert("lbl_auth_basic", "Auth Basique");
    map.insert("lbl_profile_ready", "Profil Créé !");
    map.insert("msg_profile_ready", "Les prompts ont été générés et le profil '{}' est prêt.");
    map.insert("chk_verify_cursor", "🔍 Vérifier le placement du curseur avant clic ou écriture");
    map.insert("chk_detect_activity", "⏸ Pause auto si l'utilisateur est actif (souris/clavier)");
    map.insert("chk_ssd_savings", "💾 Économiser le SSD (ne pas écrire les captures d'écran sur le disque)");
    map.insert("chk_keep_screen_awake", "🔌 Garder l'écran actif pendant l'orchestration");
    map.insert("lbl_capture_save_folder", "📁 Dossier de sauvegarde :");
    map.insert("tip_capture_save_folder", "Sélectionnez le dossier où enregistrer les captures d'écran (lorsque l'économie SSD est désactivée).");
    map.insert("btn_choose_folder", "📁 Choisir...");
    map.insert("status_user_active", "Utilisateur actif - En attente...");
    map.insert("lbl_save_success", "Sauvegarde Réussie");
    map.insert("msg_profile_saved", "Le profil '{}' a été sauvegardé avec succès !");
    map.insert("msg_config_saved", "La configuration a été sauvegardée avec succès !");
    map.insert("msg_global_config_saved", "La configuration globale a été sauvegardée avec succès !");
    map.insert("msg_engine_saved", "Le moteur '{}' a été sauvegardé avec succès !");
    map.insert("replay_from_here", "🔄 Reprendre à partir d'ici");
    map.insert("restart_step", "⏯ Refaire cette étape");
    map.insert("mark_completed", "✅ Marquer comme terminée");
    map.insert("mark_pending", "⏳ Marquer comme en attente");

    // Macro recorder tab localization keys
    map.insert("macro_heading", "🔴 Enregistreur & Rejoueur d’Actions (Macro Standalone)");
    map.insert("macro_subheading", "Préparez votre session, capturez vos actions, modifiez le graphe et relancez le rejeu.");
    map.insert("macro_step1_title", "1️⃣ ÉTAPE 1 : Session & Raccourcis Globaux");
    map.insert("macro_session_active", "📁 Session & Run Actif");
    map.insert("macro_run_label", "Nom du Run :");
    map.insert("macro_btn_new", "➕ Nouveau");
    map.insert("macro_btn_delete", "🗑️ Supprimer");
    map.insert("macro_btn_save", "💾 Sauvegarder");
    map.insert("macro_tip_save", "Enregistrer immédiatement les Runs et raccourcis sur le disque");
    map.insert("msg_macro_save_title", "💾 Confirmation de Sauvegarde Macro");
    map.insert("msg_macro_save_text", "Voulez-vous enregistrer définitivement la session, les Runs, les options et les raccourcis actuels sur le disque ?");
    map.insert("msg_macro_save_success", "💾 Session, options et Runs macro sauvegardés avec succès !");
    map.insert("macro_stats_box", "📊 Statistiques d'Exécution du Run");
    map.insert("macro_stats_launches", "🚀 Lancements totaux :");
    map.insert("macro_stats_executed_iters", "🔄 Itérations exécutées :");
    map.insert("macro_stats_completed_runs", "✅ Runs complets sans interruption :");
    map.insert("macro_stats_interruptions", "⏹️ Interruptions :");
    map.insert("macro_btn_close_editor", "❌ Fermer");
    map.insert("macro_lbl_remaining_iters", "Restantes : {}");
    map.insert("macro_tab_graph_view", "📊 Vue Graphique");
    map.insert("macro_tab_text_view", "📝 Vue Éditeur Texte / Protocole IA");
    map.insert("macro_btn_script_to_graph", "🔄 Convertir Texte ➔ Graphe");
    map.insert("macro_btn_graph_to_script", "🔄 Générer Protocole Texte");
    map.insert("macro_btn_copy_script", "📋 Copier le Protocole Texte");
    map.insert("macro_btn_export_file", "📤 Exporter Script (.txt)");
    map.insert("macro_btn_import_file", "📥 Importer Script (.txt)");
    map.insert("macro_ai_protocol_tip", "✨ Protocole IA : Collez un script généré par l'IA (Qwen / LLM) ou rédigez vos actions sous forme de commandes texte simples.");
    map.insert("macro_hotkeys_title", "🎮 Raccourcis Globaux (Capture ou Édition Directe)");
    map.insert("macro_hotkey_start", "Démarrer :");
    map.insert("macro_hotkey_stop", "Arrêter :");
    map.insert("macro_btn_capture", "🎮 Capturer");
    map.insert("macro_capture_press_key", "⌨️ Pressez votre raccourci (ex: Alt + S)...");
    map.insert("macro_capture_detected", "⌨️ Détecté :");
    map.insert("macro_btn_validate", "✅ Valider");
    map.insert("macro_btn_cancel", "❌");
    map.insert("macro_hotkey_tip", "💡 Cliquez sur 🎮 Capturer puis effectuez votre combinaison (ou tapez 'Alt + S').");
    map.insert("macro_step2_title", "2️⃣ ÉTAPE 2 : Capture & Enregistrement");
    map.insert("macro_btn_stop_record", "⏹️ Arrêter l'Enregistrement");
    map.insert("macro_btn_start_record", "🔴 Démarrer l'Enregistrement");
    map.insert("macro_lbl_record_delay", "⏳ Attente avant enregistrement :");
    map.insert("macro_unit_seconds", "secondes");
    map.insert("macro_chrono_rec_start", "⏱️ TOP DÉPART ENREGISTREMENT DANS {} SECONDE(S)... (Préparez vos fenêtres)");
    map.insert("macro_step3_title", "3️⃣ ÉTAPE 3 : Graphe d'Actions & Édition");
    map.insert("macro_btn_add_action", "➕ Ajouter Action");
    map.insert("macro_btn_undo", "↩️ Annuler (Ctrl+Z)");
    map.insert("macro_btn_redo", "↪️ Rétablir (Ctrl+Y)");
    map.insert("macro_tip_undo", "Annuler la dernière modification du graphe d'actions (Ctrl+Z)");
    map.insert("macro_tip_redo", "Rétablir la dernière modification annulée (Ctrl+Y)");
    map.insert("macro_btn_clear_run", "🧹 Vider le Run");
    map.insert("macro_no_actions", "Aucune action enregistrée pour ce Run. Cliquez sur '🔴 Démarrer l'Enregistrement' ou utilisez votre raccourci global.");
    map.insert("macro_action_count", "📊 Séquence d'Actions ({}) nœuds");
    map.insert("macro_lbl_delay_ms", "Délai (ms) :");
    map.insert("macro_in_progress", "▶️ EN COURS (Iter #{}) {}");
    map.insert("macro_edit_node_title", "⚙️ Édition du Nœud d'Action");
    map.insert("macro_lbl_action_type", "Type d'action :");
    map.insert("macro_type_keypress", "⌨️ Touche unique (KeyPress)");
    map.insert("macro_type_keyhold", "⌨️ Touche maintenue (KeyHold)");
    map.insert("macro_type_keycombo", "⌨️ Combinaison de touches (KeyCombo)");
    map.insert("macro_type_click", "🖱️ Clic souris (Click)");
    map.insert("macro_type_mousedown", "🖱️ Presser bouton (MouseDown)");
    map.insert("macro_type_mouseup", "🖱️ Relâcher bouton (MouseUp)");
    map.insert("macro_type_drag", "🖱️ Glisser-déposer (DragAndDrop)");
    map.insert("macro_type_move", "🖱️ Déplacer curseur (Move)");
    map.insert("macro_type_scroll", "📜 Défilement (Scroll)");
    map.insert("macro_type_wait", "⏱️ Attente (Wait)");
    map.insert("macro_btn_node_bind", "🎮 Capturer au Clavier");
    map.insert("macro_btn_double_click", "Double Clic");
    map.insert("macro_drag_from", "Départ X :");
    map.insert("macro_drag_to", "➔ Arrivée X :");
    map.insert("macro_key_label", "Touche :");
    map.insert("macro_hold_duration_ms", "Durée d'appui (ms) :");
    map.insert("macro_key_combo_title", "⌨️ Touches de la combinaison simultanée :");
    map.insert("macro_wait_duration_ms", "Durée d'attente (ms) :");
    map.insert("macro_step4_title", "4️⃣ ÉTAPE 4 : Lancement & Rejeu");
    map.insert("macro_btn_stop_play", "⏹️ Stopper la Lecture");
    map.insert("macro_btn_start_play", "▶️ Lancer la Macro (Jouer)");
    map.insert("macro_lbl_iterations", "🔄 Itérations :");
    map.insert("macro_lbl_play_delay", "⏳ Attente avant lecture :");
    map.insert("macro_unit_sec", "sec");
    map.insert("macro_chk_global_pacing", "⏱️ Cadence globale (ms)");
    map.insert("macro_chrono_play_start", "⏱️ TOP DÉPART LECTURE DANS {} SECONDE(S)... (Préparer l'écran)");
    map
}

pub fn lexicon_en() -> std::collections::HashMap<&'static str, &'static str> {
    let mut map = std::collections::HashMap::new();
    map.insert("frame_cible", " Global Configuration (AI Engine, Monitored Apps & Profiles) ");
    map.insert("tab_config", " ⚙ Global Configuration ");
    map.insert("tab_setup", " ⛭ Setup ");
    map.insert("tab_quickstart", " ❖ Help - Quick Start ");
    map.insert("tab_prompts", " ✎ Prompt Editor ");
    map.insert("tab_console", " ➤ Console & Monitor ");
    map.insert("tab_task_graph", " 🪵 Task Graph ");
    map.insert("frame_generateur", " ✨ AI Prompt Generator ");
    map.insert("frame_timeline", " 🌐 Action Visual Timeline (Git Commit-Style) ");
    map.insert("frame_logs", " 🔴 Real-time Activity Console & Logs ");
    map.insert("lbl_langue", "Language:");
    map.insert("lbl_profil", "Profile:");
    map.insert("lbl_selection_fenetres", "Target Windows:");
    map.insert("lbl_context", "0. General Situation Context:");
    map.insert("lbl_obj", "2. Stop Condition (Do While / Limits):");
    map.insert("lbl_tsk", "1. Global Task to Accomplish (Starting Instructions):");
    map.insert("lbl_dir", "3. Specific System Directives (AI Rules):");
    map.insert("lbl_moteur", "Engine:");
    map.insert("lbl_url", "API URL:");
    map.insert("lbl_modele", "Model:");
    map.insert("chk_son", "🔔 Sound notification");
    map.insert("chk_tooltips", "💬 Active tooltips");
    map.insert("btn_reinit", "🔄 Reset All");
    map.insert("btn_sauver", "💾 Save Profile");
    map.insert("btn_opti_court", "🪄 Optimize this field");
    map.insert("btn_clear_logs", "🗑️ Clear Logs");
    map.insert("btn_copy_logs", "📋 Copy Logs");
    map.insert("btn_copy_report", "📋 Copy Report");
    map.insert("btn_generer_tout", "✨ Generate Prompts");
    map.insert("btn_lancer", "🚀 Start");
    map.insert("btn_arreter", "⏹️ Stop");
    map.insert("btn_resume", "▶️ Resume");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_stop_demande", "⏹️ Stop requested by user.");
    map.insert("status_arrete", "⏹️ Stopped.");
    map.insert("btn_pause", "⏸️ PAUSE");
    map.insert("btn_reprendre", "▶️ RESUME AUTO");
    map.insert("btn_charger", "📂 Load");
    map.insert("btn_sauver_profil", "💾 Save");
    map.insert("btn_supprimer", "🗑️ Delete");
    map.insert("statut_pret", "Status: Ready");
    map.insert("statut_pause", "Status: Paused");
    map.insert("statut_reprise", "💾 A previous session was detected. Ready to resume!");
    map.insert("msg_reinit", "🔄 Everything has been reset to default!");
    map.insert("msg_sauve", "💾 Texts, language, and state saved!");
    map.insert("msg_vide", "⚠️ Please write your need or fill the selected field first!");
    map.insert("lbl_aucune_fenetre", "🖥️ All Screens (no target window specified)");
    map.insert("msg_opti_en_cours", "🪄 Qwen is optimizing the selected field...");
    map.insert("msg_opti_ok", "✅ Field optimized by AI!");
    map.insert("msg_gen_en_cours", "⚡ Building complete prompt configuration using AI...");
    map.insert("msg_gen_ok", "✅ All orchestration prompts successfully generated by AI!");
    map.insert("msg_confirm_titre", "Confirm Save");
    map.insert("msg_confirm_texte", "Warning: Do you really want to save and overwrite prompts and settings for profile '{}'?");
    map.insert("msg_confirm_texte_generique", "Warning: Do you want to save current prompts as the default profile (save.enc)?");
    map.insert("msg_nom_profil_titre", "New Profile");
    map.insert("msg_nom_profil_texte", "Enter the name of the new configuration profile:");
    map.insert("msg_nom_moteur_titre", "New AI Engine");
    map.insert("msg_nom_moteur_texte", "Enter the name of the new engine profile:");
    map.insert("msg_moteur_sauve", "✅ Engine profile saved!");
    map.insert("msg_moteur_supprime", "🗑️ Engine profile deleted!");
    map.insert("msg_confirm_supp_moteur_titre", "Confirm Deletion");
    map.insert("msg_confirm_supp_moteur_texte", "Are you sure you want to permanently delete engine '{}'?");
    map.insert("msg_confirm_gen_titre", "Confirm Global Generation");
    map.insert("msg_confirm_gen_texte", "Warning: Generation will overwrite all your current prompts. Do you want to continue?");
    map.insert("msg_profil_sauve", "✅ Profile saved successfully!");
    map.insert("msg_profil_charge", "📂 Profile loaded successfully!");
    map.insert("msg_profil_supprime", "🗑️ Profile deleted!");
    map.insert("msg_confirm_supp_titre", "Confirm Deletion");
    map.insert("msg_confirm_supp_texte", "Are you sure you want to permanently delete profile '{}'?");
    map.insert("btn_oui", "Yes");
    map.insert("btn_non", "Cancel");
    map.insert("legende_think", "T: Thinking");
    map.insert("legende_wait", "W: App Busy");
    map.insert("legende_cool", "CD: Stabilizing");
    map.insert("legende_scroll", "S: Scroll");
    map.insert("legende_click", "C: Type");
    map.insert("legende_success", "★: Success");
    map.insert("legende_fail", "X: Fail");
    map.insert("legende_sleep", "SL: Sleep/Lock");
    map.insert("legende_static", "ST: Static Screen");
    map.insert("log_screen_asleep", "⏳ Screen is asleep or locked. Waiting 5s...");
    map.insert("log_static_screen", "⏳ Static screen detected (no change). Waiting 10s...");
    map.insert("status_screen_asleep", "⏳ Screen asleep or locked...");
    map.insert("status_static_screen", "⏳ Static screen...");
    map.insert("all_screens", "ALL SCREENS (Virtual Desktop)");
    map.insert("screen_title", "Desktop - Screen {}");
    map.insert("frame_ia", " 1. AI Engine & Model (Vision LLM) ");
    map.insert("frame_windows", " 2. Monitored Target Applications ");
    map.insert("frame_profils", " 3. Profile Management ");
    map.insert("tip_frame_ia", "Configure the local or remote AI API provider and VLM model to analyze the screen.");
    map.insert("tip_frame_windows", "Select and manage the list of windows to watch. If empty, the entire screen is watched.");
    map.insert("tip_frame_profils", "Load, save, or delete complete sets of prompts and target window setups.");
    map.insert("tip_context", "Starting context to help the AI's vision (OS, tools, initial state).");
    map.insert("tip_tsk", "Main action instructions for the AI to interact with the interface (in technical English).");
    map.insert("tip_obj", "Final visually verifiable objective for the AI to know when to stop (in technical English).");
    map.insert("tip_dir", "Strict safety instructions and behavioral rules to guide the AI (in technical English).");
    map.insert("tip_refresh", "Refresh the active desktop window list");
    map.insert("tip_add_win", "Add the selected window to your watch list");
    map.insert("tip_del_win", "Remove selected window from your watch list");
    map.insert("tip_add_engine", "Add a new AI provider profile (LM Studio, Ollama...)");
    map.insert("tip_del_engine", "Delete currently selected AI provider profile");
    map.insert("tip_load_profile", "Load prompts and setup from this profile");
    map.insert("tip_save_profile", "Create a new profile or overwrite current");
    map.insert("tip_del_profile", "Permanently delete this profile from disk");
    map.insert("tip_optimize_field", "Ask local AI to reformulate this field in precise tech English");
    map.insert("tip_generate_all", "Ask AI to generate the complete orchestrator prompts based on your idea");
    map.insert("tip_clear_memory", "Delete resume/active work memory to start with a blank page");
    map.insert("log_fenetres_invisibles", "⏳ No monitored application is visible (minimized or closed). Waiting 5s...");
    map.insert("status_fenetres_invisibles", "⏳ Waiting for target windows...");
    map.insert("log_detection_occupe", "⏳ Detection {} : BUSY. Waiting...");
    map.insert("log_detection_libre", "⏳ Detection {} : FREE.");
    map.insert("log_fenetre_ajoutee", "➕ Window added to watch list: {}");
    map.insert("log_fenetre_retiree", "🗑️ Window removed from watch list: {}");
    map.insert("log_ia_adapte", "⚙️ AI parameters adapted for {}.");
    map.insert("log_moteur_enregistre", "💾 New AI engine profile saved: {}");
    map.insert("log_impossible_suppr_dernier", "⚠️ Cannot delete the last remaining engine.");
    map.insert("log_moteur_supprime", "🗑️ Engine profile deleted: {}");
    map.insert("log_profil_charge", "📂 Profile loaded: {}");
    map.insert("log_profil_supprime", "🗑️ Profile deleted: {}");
    map.insert("log_champ_optimise", "🪄 AI: Field '{}' optimized.");
    map.insert("log_gen_demandee", "⚡ Global auto-generation requested...");
    map.insert("log_gen_injectee", "⚡ Global configuration generated and injected.");
    map.insert("log_lancement_moteur", "🚀 Launching with engine: {} ({})");
    map.insert("log_pause", "⏸️ Automator paused.");
    map.insert("log_reprise", "▶️ Resuming automator.");
    map.insert("log_reflexion_ia", "🧠 [THINKING AI] Capture and sending for analysis by {}...");
    map.insert("log_succes", "★ Automation completed with SUCCESS!");
    map.insert("log_echec", "X Automation completed with FAILURE.");
    map.insert("log_attente_occupee", "⏳ [TASK WAIT] Target application is busy. Pause of {}s...");
    map.insert("log_lancement_visual", "📱 Launching VibePilot Visual Orchestrator.");
    map.insert("log_linux_detecte", "🐧 Linux OS detected.");
    map.insert("log_warning_wayland", "⚠️ [WARNING WAYLAND] Active Wayland session. Please use X11 for mouse clicks to work properly.");
    map.insert("log_x11_detecte", "✅ X11 display server detected. Ready for automation.");
    map.insert("log_sec_save", "[SECURITY] Configuration saved.");
    map.insert("log_error_opti", "❌ Error during optimization: {}");
    map.insert("msg_attente_inactivite", "⏳ Waiting for idle state ({}s)...");
    map.insert("status_reprise_init", "🔄 RESUMING...");
    map.insert("status_initialisation", "🚀 INITIALIZATION...");
    map.insert("status_reflexion", "🧠 [AI THINKING] {} is thinking...");
    map.insert("status_ia_decide", "🤖 AI: {}");
    map.insert("status_cooldown", "⏳ Cool-down ({}s)...");
    map.insert("status_waiting", "⏳ Waiting ({}s)...");
    map.insert("err_load_profile", "❌ Error loading profile: {}");
    map.insert("err_generic", "❌ Error: {}");
    map.insert("tip_clear_memory", "Delete resume/active work memory to start with a blank page");
    map.insert("log_memory_cleared", "Active work/resume memory cleared successfully.");
    map.insert("btn_resume", "Resume");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_reprise_existants", "💾 Resuming session: using existing prompts. To start a new goal, click 'Reset' first.");
    map.insert("chk_theme_sombre", "🌙 Dark Theme");
    map.insert("chk_auto_validate", "🔒 Auto-validate Standard Actions");
    map.insert("chk_auto_validate_dangerous", "🔒 Auto-validate Dangerous Commands");
    map.insert("tip_auto_validate", "If enabled, standard AI actions (like clicks and scrolls) are executed without manual confirmation.");
    map.insert("tip_auto_validate_dangerous", "If enabled, potentially dangerous terminal commands (e.g. rm, format, sudo) are automatically validated.");
    map.insert("tip_zoom_facteur", "Sets the zoom/scaling level of the user interface. Useful if the application appears too small or too large on your screen.");
    map.insert("security_warning_titre", "⚠️ AI Actions");
    map.insert("security_warning_texte", "The AI has decided the following actions:\n\n{actions}\n\nDo you want to execute them?");
    map.insert("security_warning_yes", "✅ Execute");
    map.insert("security_warning_no", "❌ Cancel");
    map.insert("btn_add_engine", "➕");
    map.insert("btn_del_engine", "🗑️");
    map.insert("btn_add_window", "➕");
    map.insert("btn_refresh_windows", "🔄");
    map.insert("lbl_auth_mode", "Authentication:");
    map.insert("lbl_api_key", "API Key:");
    map.insert("lbl_auth_login", "Username:");
    map.insert("lbl_auth_password", "Password:");
    map.insert("lbl_request_timeout", "Request Timeout (sec):");
    map.insert("lbl_auth_none", "None");
    map.insert("lbl_auth_api_key", "API Key");
    map.insert("lbl_auth_basic", "Basic Auth");
    map.insert("lbl_profile_ready", "Profile Created!");
    map.insert("msg_profile_ready", "The prompts are generated and the profile '{}' is ready.");
    map.insert("chk_verify_cursor", "🔍 Verify cursor placement before click or write");
    map.insert("chk_detect_activity", "⏸ Auto-pause on user activity (mouse/keyboard)");
    map.insert("chk_ssd_savings", "💾 SSD Write Savings (do not write screenshots to disk)");
    map.insert("chk_keep_screen_awake", "🔌 Keep screen awake during orchestration");
    map.insert("lbl_capture_save_folder", "📁 Save folder:");
    map.insert("tip_capture_save_folder", "Select the folder where screenshots will be saved (when SSD Write Savings is disabled).");
    map.insert("btn_choose_folder", "📁 Choose...");
    map.insert("status_user_active", "User active - Waiting...");
    map.insert("lbl_save_success", "Save Successful");
    map.insert("msg_profile_saved", "Profile '{}' saved successfully!");
    map.insert("msg_config_saved", "Configuration saved successfully!");
    map.insert("msg_global_config_saved", "Global configuration saved successfully!");
    map.insert("msg_engine_saved", "Engine '{}' saved successfully!");
    map.insert("replay_from_here", "🔄 Replay from here");
    map.insert("restart_step", "⏯ Restart this step");
    map.insert("mark_completed", "✅ Mark as Completed");
    map.insert("mark_pending", "⏳ Mark as Pending");

    // Macro recorder tab localization keys
    map.insert("macro_heading", "🔴 Action Recorder & Player (Standalone Macro)");
    map.insert("macro_subheading", "Prepare your session, capture your actions, edit the graph, and launch playback.");
    map.insert("macro_step1_title", "1️⃣ STEP 1: Session & Global Hotkeys");
    map.insert("macro_session_active", "📁 Session & Active Run");
    map.insert("macro_run_label", "Run Name:");
    map.insert("macro_btn_new", "➕ New");
    map.insert("macro_btn_delete", "🗑️ Delete");
    map.insert("macro_btn_save", "💾 Save");
    map.insert("macro_tip_save", "Immediately save Runs and hotkeys to disk");
    map.insert("msg_macro_save_title", "💾 Macro Save Confirmation");
    map.insert("msg_macro_save_text", "Do you want to permanently save the current session, Runs, options, and hotkeys to disk?");
    map.insert("msg_macro_save_success", "💾 Macro session, options, and Runs saved successfully!");
    map.insert("macro_stats_box", "📊 Run Execution Statistics");
    map.insert("macro_stats_launches", "🚀 Total launches:");
    map.insert("macro_stats_executed_iters", "🔄 Iterations executed:");
    map.insert("macro_stats_completed_runs", "✅ Completed runs without interruption:");
    map.insert("macro_stats_interruptions", "⏹️ Interruptions:");
    map.insert("macro_btn_close_editor", "❌ Close");
    map.insert("macro_lbl_remaining_iters", "Remaining: {}");
    map.insert("macro_tab_graph_view", "📊 Graph View");
    map.insert("macro_tab_text_view", "📝 Text Script & AI Protocol View");
    map.insert("macro_btn_script_to_graph", "🔄 Parse Text to Graph");
    map.insert("macro_btn_graph_to_script", "🔄 Export Graph to Text Protocol");
    map.insert("macro_btn_copy_script", "📋 Copy Protocol Script");
    map.insert("macro_btn_export_file", "📤 Export Script File (.txt)");
    map.insert("macro_btn_import_file", "📥 Import Script File (.txt)");
    map.insert("macro_ai_protocol_tip", "✨ AI Protocol: Paste a script generated by AI (Qwen / LLM) or write your actions using simple text commands.");
    map.insert("macro_hotkeys_title", "🎮 Global Hotkeys (Capture or Direct Edit)");
    map.insert("macro_hotkey_start", "Start:");
    map.insert("macro_hotkey_stop", "Stop:");
    map.insert("macro_btn_capture", "🎮 Capture");
    map.insert("macro_capture_press_key", "⌨️ Press your shortcut (e.g. Alt + S)...");
    map.insert("macro_capture_detected", "⌨️ Detected:");
    map.insert("macro_btn_validate", "✅ Confirm");
    map.insert("macro_btn_cancel", "❌");
    map.insert("macro_hotkey_tip", "💡 Click 🎮 Capture then perform your key combination (or type 'Alt + S').");
    map.insert("macro_step2_title", "2️⃣ STEP 2: Capture & Recording");
    map.insert("macro_btn_stop_record", "⏹️ Stop Recording");
    map.insert("macro_btn_start_record", "🔴 Start Recording");
    map.insert("macro_lbl_record_delay", "⏳ Delay before recording:");
    map.insert("macro_unit_seconds", "seconds");
    map.insert("macro_chrono_rec_start", "⏱️ RECORDING COUNTDOWN: {} SECOND(S)... (Prepare your windows)");
    map.insert("macro_step3_title", "3️⃣ STEP 3: Action Graph & Editing");
    map.insert("macro_btn_add_action", "➕ Add Action");
    map.insert("macro_btn_undo", "↩️ Undo (Ctrl+Z)");
    map.insert("macro_btn_redo", "↪️ Redo (Ctrl+Y)");
    map.insert("macro_tip_undo", "Undo last action graph modification (Ctrl+Z)");
    map.insert("macro_tip_redo", "Redo last undone modification (Ctrl+Y)");
    map.insert("macro_btn_clear_run", "🧹 Clear Run");
    map.insert("macro_no_actions", "No actions recorded for this Run. Click '🔴 Start Recording' or use your global hotkey.");
    map.insert("macro_action_count", "📊 Action Sequence ({}) nodes");
    map.insert("macro_lbl_delay_ms", "Delay (ms):");
    map.insert("macro_in_progress", "▶️ PLAYING (Iter #{}) {}");
    map.insert("macro_edit_node_title", "⚙️ Action Node Editor");
    map.insert("macro_lbl_action_type", "Action Type:");
    map.insert("macro_type_keypress", "⌨️ Single Key (KeyPress)");
    map.insert("macro_type_keyhold", "⌨️ Key Hold (KeyHold)");
    map.insert("macro_type_keycombo", "⌨️ Key Combination (KeyCombo)");
    map.insert("macro_type_click", "🖱️ Mouse Click (Click)");
    map.insert("macro_type_mousedown", "🖱️ Press Mouse Button (MouseDown)");
    map.insert("macro_type_mouseup", "🖱️ Release Mouse Button (MouseUp)");
    map.insert("macro_type_drag", "🖱️ Drag and Drop (DragAndDrop)");
    map.insert("macro_type_move", "🖱️ Move Cursor (Move)");
    map.insert("macro_type_scroll", "📜 Scroll (Scroll)");
    map.insert("macro_type_wait", "⏱️ Wait (Wait)");
    map.insert("macro_btn_node_bind", "🎮 Key Capture");
    map.insert("macro_btn_double_click", "Double Click");
    map.insert("macro_drag_from", "Start X:");
    map.insert("macro_drag_to", "➔ End X:");
    map.insert("macro_key_label", "Key:");
    map.insert("macro_hold_duration_ms", "Hold duration (ms):");
    map.insert("macro_key_combo_title", "⌨️ Simultaneous Key Combination Keys:");
    map.insert("macro_wait_duration_ms", "Wait duration (ms):");
    map.insert("macro_step4_title", "4️⃣ STEP 4: Launch & Playback");
    map.insert("macro_btn_stop_play", "⏹️ Stop Playback");
    map.insert("macro_btn_start_play", "▶️ Play Macro");
    map.insert("macro_lbl_iterations", "🔄 Iterations:");
    map.insert("macro_lbl_play_delay", "⏳ Delay before playback:");
    map.insert("macro_unit_sec", "sec");
    map.insert("macro_chk_global_pacing", "⏱️ Global pacing (ms)");
    map.insert("macro_chrono_play_start", "⏱️ PLAYBACK COUNTDOWN: {} SECOND(S)... (Prepare screen)");
    map
}

// --- AI Prompts ---
pub const PROMPT_OPTIMIZE_CONTEXT: &str =
    "You are an expert Prompt Engineer. Take the raw situation context description and rewrite it into a clean, concise, precise description of the system, tools, and layout in English.\n\
     Return ONLY the final optimized text in crisp English without markdown or quotes.";

pub const PROMPT_OPTIMIZE_OBJECTIF: &str =
    "You are an expert Prompt Engineer. Take the user's raw goal/stop condition and rewrite it into a single, clean, precise logical sentence in English.\n\
     It must describe a clear, visually verifiable end-state.\n\
     Return ONLY the final optimized sentence in crisp English without markdown or quotes.";

pub const PROMPT_OPTIMIZE_TASK: &str =
    "You are an expert Prompt Engineer. Take the raw intention of the user and rewrite it into clean, precise, operational directives in English.\n\
     State clearly that the AI is the PC operator piloting the workspace interface.\n\
     Return ONLY the final optimized prompt in crisp English without markdown.";

pub const PROMPT_OPTIMIZE_DIRECTIVES: &str =
    "You are an expert Prompt Engineer. Take the raw operational rules and rewrite them into a structured, clear list of conditional rules (bullet points) in English for a Vision LLM to follow on screen.\n\
     Keep them highly operational. Return ONLY the final optimized bullet list in English without markdown.";

pub const PROMPT_OPTIMIZE_FEEDBACK: &str =
    "You are an expert Prompt Engineer. Take the user's raw operational feedback, correction, or hint for an automation task and rewrite it into a clear, concise, highly precise instruction in English for a Vision LLM to execute.\n\
     Keep it short and extremely actionable. Return ONLY the final optimized text in crisp English without markdown or quotes.";

pub const PROMPT_GLOBAL_GENERATION: &str =
    "You are an expert AI Architect and Prompt Engineer.\n\
     Your role is to translate a simple user request into a complete, structured configuration for a visual AI automation agent (Qwen-VL).\n\n\
     Given the user request, you must output a strict JSON object with EXACTLY four fields:\n\
     1. \"contexte\": A clear, concise description in English of the operating environment, OS, active tools, and initial setup state.\n\
     2. \"objectif\": A precise, visually verifiable logical condition in English representing the final success state.\n\
     3. \"task\": A clear, high-level directive in English explaining to the AI how to pilot the target application's interface to accomplish the goal.\n\
     4. \"directives\": A structured, clear bulleted list in English detailing the specific conditional system rules. You MUST NOT leave this field empty. If no specific directives are obvious, generate 3-4 default helpful operational rules (e.g. regarding waiting for app load, scrolling on overflow, or verifying actions).\n\n\
     You MUST respond ONLY with the raw JSON object (enclosed in { and }). No markdown block wrappers, no introduction, no explanation.";
