//! Lexicon (UI translations) and Prompts (AI instructions).

pub fn lexicon_fr() -> std::collections::HashMap<&'static str, &'static str> {
    let mut map = std::collections::HashMap::new();
    map.insert("frame_cible", " Configuration Globale (Moteur IA, Applications & Profils) ");
    map.insert("tab_config", " ⚙ Configuration Globale ");
    map.insert("tab_setup", " ⛭ Setup ");
    map.insert("tab_quickstart", " ❖ Aide - Démarrage Rapide ");
    map.insert("tab_prompts", " ✎ Éditeur de Prompts ");
    map.insert("tab_console", " ➤ Console & Supervision ");
    map.insert("frame_generateur", " ✨ Générateur de consigne rapide par l'IA ");
    map.insert("frame_timeline", " 🌐 Timeline Visuelle des Actions (Git Commit-Style) ");
    map.insert("frame_logs", " 🔴 Console d'Activité & Logs Temps Réel ");
    map.insert("lbl_langue", "Langue :");
    map.insert("lbl_profil", "Profil :");
    map.insert("lbl_selection_fenetres", "Fenêtres à suivre :");
    map.insert("lbl_context", "0. Contexte général de la situation :");
    map.insert("lbl_obj", "2. Condition d'arrêt (Do While / Limites) :");
    map.insert("lbl_tsk", "1. Tâche globale à accomplir (Consigne de départ) :");
    map.insert("lbl_dir", "3. Directives système spécifiques (Règles de l'IA) :");
    map.insert("lbl_moteur", "Moteur :");
    map.insert("lbl_url", "URL API :");
    map.insert("lbl_modele", "Modèle :");
    map.insert("chk_son", "🔔 Notification sonore");
    map.insert("chk_tooltips", "💬 Info-bulles actives");
    map.insert("btn_reinit", "🔄 Réinitialiser tout");
    map.insert("btn_sauver", "💾 Sauvegarder profil");
    map.insert("btn_opti_court", "🪄 Optimiser ce champ");
    map.insert("btn_clear_logs", "🗑️ Effacer les logs");
    map.insert("btn_generer_tout", "✨ Générer la configuration");
    map.insert("btn_lancer", "🚀 Lancer");
    map.insert("btn_arreter", "⏹️ Arrêter");
    map.insert("btn_resume", "▶️ Reprendre");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_stop_demande", "⏹️ Arrêt demandé par l'utilisateur.");
    map.insert("status_arrete", "⏹️ Arrêté.");
    map.insert("btn_pause", "⏸️ PAUSE");
    map.insert("btn_reprendre", "▶️ REPRENDRE L'AUTO");
    map.insert("btn_charger", "📂 Charger");
    map.insert("btn_sauver_profil", "💾 Sauver");
    map.insert("btn_supprimer", "🗑️ Suppr.");
    map.insert("statut_pret", "Statut : Prêt");
    map.insert("statut_pause", "Statut : En Pause");
    map.insert("statut_reprise", "💾 Une session précédente a été détectée. Prêt à reprendre !");
    map.insert("msg_reinit", "🔄 Tout a été réinitialisé à zéro !");
    map.insert("msg_sauve", "💾 Textes, langue et état sauvegardés !");
    map.insert("msg_vide", "⚠️ Écris d'abord ton besoin ou remplis le champ sélectionné !");
    map.insert("lbl_aucune_fenetre", "🖥️ Tout l'écran (aucune application cible spécifiée)");
    map.insert("msg_opti_en_cours", "🪄 Qwen optimise le champ sélectionné...");
    map.insert("msg_opti_ok", "✅ Champ optimisé par l'IA !");
    map.insert("msg_gen_en_cours", "⚡ Configuration de l'ensemble de l'orchestration par l'IA...");
    map.insert("msg_gen_ok", "✅ Tous les champs de prompt ont été structurés par l'IA !");
    map.insert("msg_confirm_titre", "Confirmation de sauvegarde");
    map.insert("msg_confirm_texte", "Attention : Voulez-vous sauvegarder les prompts et réglages actuels dans le profil '{}' ?");
    map.insert("msg_confirm_texte_generique", "Attention : Voulez-vous sauvegarder la configuration actuelle en tant que profil par défaut (save.enc) ?");
    map.insert("msg_nom_profil_titre", "Nouveau Profil");
    map.insert("msg_nom_profil_texte", "Saisissez le nom du nouveau profil de configuration :");
    map.insert("msg_nom_moteur_titre", "Nouveau Moteur IA");
    map.insert("msg_nom_moteur_texte", "Saisissez le nom du nouveau profil de moteur :");
    map.insert("msg_moteur_sauve", "✅ Moteur enregistré !");
    map.insert("msg_moteur_supprime", "🗑️ Moteur supprimé !");
    map.insert("msg_confirm_supp_moteur_titre", "Confirmer la suppression");
    map.insert("msg_confirm_supp_moteur_texte", "Voulez-vous vraiment supprimer définitivement le moteur '{}' ?");
    map.insert("msg_confirm_gen_titre", "Confirmer la génération globale");
    map.insert("msg_confirm_gen_texte", "Attention : La génération par l'IA va écraser l'ensemble de tes prompts actuels. Es-tu sûr de vouloir continuer ?");
    map.insert("msg_profil_sauve", "✅ Profil sauvegardé avec succès !");
    map.insert("msg_profil_charge", "📂 Profil chargé avec succès !");
    map.insert("msg_profil_supprime", "🗑️ Profil supprimé !");
    map.insert("msg_confirm_supp_titre", "Confirmer suppression");
    map.insert("msg_confirm_supp_texte", "Voulez-vous vraiment supprimer définitivement le profil '{}' ?");
    map.insert("btn_oui", "Oui");
    map.insert("btn_non", "Annuler");
    map.insert("legende_think", "T : Réflexion IA");
    map.insert("legende_wait", "W : App occupée");
    map.insert("legende_cool", "CD : Stabilisation");
    map.insert("legende_scroll", "S : Défiler");
    map.insert("legende_click", "C : Saisie");
    map.insert("legende_success", "★ : Succès");
    map.insert("legende_fail", "X : Échec");
    map.insert("legende_sleep", "SL : Veille/Verrou");
    map.insert("legende_static", "ST : Écran statique");
    map.insert("log_screen_asleep", "⏳ Écran en veille ou verrouillé. Attente de 5s...");
    map.insert("log_static_screen", "⏳ Écran statique détecté (aucun changement). Attente de 10s...");
    map.insert("status_screen_asleep", "⏳ Écran en veille ou verrouillé...");
    map.insert("status_static_screen", "⏳ Écran statique...");
    map.insert("all_screens", "TOUS LES ÉCRANS (Bureau virtuel)");
    map.insert("screen_title", "Bureau - Écran {}");
    map.insert("frame_ia", " 1. Fournisseur d'IA & Modèle (Vision LLM) ");
    map.insert("frame_windows", " 2. Applications cibles à surveiller ");
    map.insert("frame_profils", " 3. Gestion des Profils ");
    map.insert("tip_frame_ia", "Configure le fournisseur d'API d'IA locale ou distante ainsi que le modèle de vision à utiliser.");
    map.insert("tip_frame_windows", "Sélectionne et gère la liste des fenêtres à surveiller. Si vide, l'écran entier est surveillé.");
    map.insert("tip_frame_profils", "Charge, sauvegarde ou supprime des configurations complètes de prompts et de cibles.");
    map.insert("tip_context", "Contexte de départ pour guider la vision de l'IA (OS, outils, état de départ).");
    map.insert("tip_tsk", "Instructions d'action principales destinées à l'IA pour manipuler l'interface (en anglais technique).");
    map.insert("tip_obj", "Objectif final vérifiable visuellement pour que l'IA sache quand s'arrêter (en anglais technique).");
    map.insert("tip_dir", "Consignes de comportement et règles de sécurité strictes pour guider l'IA (en anglais technique).");
    map.insert("tip_refresh", "Rafraîchir la liste des fenêtres actives de votre bureau");
    map.insert("tip_add_win", "Ajouter l'application ciblée à la liste de surveillance");
    map.insert("tip_del_win", "Retirer l'application sélectionnée de la liste de surveillance");
    map.insert("tip_add_engine", "Ajouter un profil de fournisseur d'API d'IA (LM Studio, Ollama...)");
    map.insert("tip_del_engine", "Supprimer le profil d'IA actuellement affiché");
    map.insert("tip_load_profile", "Charger les prompts et la configuration de ce profil");
    map.insert("tip_save_profile", "Créer un nouveau profil ou écraser le profil existant");
    map.insert("tip_del_profile", "Supprimer définitivement ce profil de la mémoire");
    map.insert("tip_optimize_field", "Laisser l'IA locale reformuler et optimiser ce champ en anglais technique");
    map.insert("tip_generate_all", "Demander à l'IA de concevoir l'ensemble de l'automatisation à partir de ton idée");
    map.insert("tip_clear_memory", "Supprimer la mémoire du dernier travail en cours pour repartir à zéro");
    map.insert("log_fenetres_invisibles", "⏳ Aucune application surveillée n'est visible (minimisée ou fermée). Attente de 5s...");
    map.insert("status_fenetres_invisibles", "⏳ En attente des fenêtres cibles...");
    map.insert("log_detection_occupe", "⏳ Détection {} : OCCUPÉ. En attente...");
    map.insert("log_detection_libre", "⏳ Détection {} : LIBRE.");
    map.insert("log_fenetre_ajoutee", "➕ Fenêtre ajoutée à la surveillance : {}");
    map.insert("log_fenetre_retiree", "🗑️ Fenêtre retirée de la surveillance : {}");
    map.insert("log_ia_adapte", "⚙️ Paramètres IA adaptés pour {}.");
    map.insert("log_moteur_enregistre", "💾 Nouveau profil de moteur IA enregistré : {}");
    map.insert("log_impossible_suppr_dernier", "⚠️ Impossible de supprimer le dernier moteur restant.");
    map.insert("log_moteur_supprime", "🗑️ Moteur supprimé : {}");
    map.insert("log_profil_charge", "📂 Profil chargé : {}");
    map.insert("log_profil_supprime", "🗑️ Profil supprimé : {}");
    map.insert("log_champ_optimise", "🪄 IA : Champ '{}' optimisé.");
    map.insert("log_gen_demandee", "⚡ Génération automatique globale demandée...");
    map.insert("log_gen_injectee", "⚡ Configuration globale rédigée et injectée.");
    map.insert("log_lancement_moteur", "🚀 Lancement avec le moteur : {} ({})");
    map.insert("log_pause", "⏸️ Automate mis en pause.");
    map.insert("log_reprise", "▶️ Reprise de l'automate.");
    map.insert("log_reflexion_ia", "🧠 [RÉFLEXION IA] Capture et envoi pour analyse par {}...");
    map.insert("log_succes", "🏆 Fin de l'automatisation avec SUCCÈS !");
    map.insert("log_echec", "❌ Fin de l'automatisation avec ÉCHEC.");
    map.insert("log_attente_occupee", "⏳ [ATTENTE DE TÂCHE] L'application cible est occupée. Pause de {}s...");
    map.insert("log_lancement_visual", "📱 Lancement de l'Orchestrateur Visuel VibePilot.");
    map.insert("log_linux_detecte", "🐧 Système d'exploitation Linux détecté.");
    map.insert("log_warning_wayland", "⚠️ [WARNING WAYLAND] Session Wayland active. Veuillez utiliser X11 pour le bon fonctionnement des clics.");
    map.insert("log_x11_detecte", "✅ Serveur d'affichage X11 détecté. Prêt pour l'automatisation.");
    map.insert("log_sec_save", "[SECURITE] Configuration sauvegardée.");
    map.insert("log_error_opti", "❌ Erreur lors de l'optimisation : {}");
    map.insert("msg_attente_inactivite", "⏳ Attente inactivité ({}s)...");
    map.insert("status_reprise_init", "🔄 REPRISE...");
    map.insert("status_initialisation", "🚀 INITIALISATION...");
    map.insert("status_reflexion", "🧠 [RÉFLEXION IA] {} réfléchit...");
    map.insert("status_ia_decide", "🤖 IA : {}");
    map.insert("status_cooldown", "⏳ Cool-down ({}s)...");
    map.insert("status_waiting", "⏳ Waiting ({}s)...");
    map.insert("err_load_profile", "❌ Erreur de chargement du profil : {}");
    map.insert("err_generic", "❌ Erreur : {}");
    map.insert("log_memory_cleared", "🧹 Travail en cours/mémoire de reprise supprimé avec succès.");
    map.insert("log_reprise_existants", "💾 Reprise en cours : utilisation des prompts existants. Pour démarrer un nouvel objectif, cliquez d'abord sur 'Reset'.");
    map.insert("chk_theme_sombre", "🌙 Thème Sombre");
    map.insert("chk_auto_validate", "🔒 Auto-validation standard");
    map.insert("chk_auto_validate_dangerous", "🔒 Auto-validation commandes dangereuses");
    map.insert("tip_auto_validate", "Si activé, les actions de clic et défilement standard de l'IA sont exécutées sans confirmation.");
    map.insert("tip_auto_validate_dangerous", "Si activé, les commandes potentiellement dangereuses (ex: rm, format, sudo) sont validées automatiquement.");
    map.insert("tip_zoom_facteur", "Définit le niveau de zoom/mise à l'échelle de l'interface. Fixer à 100% ou 125% résout les bugs de redimensionnement infini sous Windows lors du déplacement entre écrans à résolutions différentes (DPI).");
    map.insert("security_warning_titre", "⚠️ Actions de l'IA");
    map.insert("security_warning_texte", "L'IA a décidé des actions suivantes :\n\n{actions}\n\nVoulez-vous les exécuter ?");
    map.insert("security_warning_yes", "✅ Exécuter");
    map.insert("security_warning_no", "❌ Annuler");
    map.insert("btn_add_engine", "➕");
    map.insert("btn_del_engine", "🗑️");
    map.insert("btn_add_window", "➕");
    map.insert("btn_refresh_windows", "🔄");
    map.insert("lbl_auth_mode", "Authentification :");
    map.insert("lbl_api_key", "Clé API :");
    map.insert("lbl_auth_login", "Identifiant :");
    map.insert("lbl_auth_password", "Mot de passe :");
    map.insert("lbl_request_timeout", "Timeout Requête (sec) :");
    map.insert("lbl_auth_none", "Aucune");
    map.insert("lbl_auth_api_key", "Clé API");
    map.insert("lbl_auth_basic", "Auth Basique");
    map.insert("lbl_profile_ready", "Profil Créé !");
    map.insert("msg_profile_ready", "Les prompts ont été générés et le profil '{}' est prêt.");
    map.insert("chk_verify_cursor", "🔍 Vérifier le placement du curseur avant clic ou écriture");
    map.insert("chk_detect_activity", "⏸ Pause auto si l'utilisateur est actif (souris/clavier)");
    map.insert("status_user_active", "Utilisateur actif - En attente...");
    map
}

pub fn lexicon_en() -> std::collections::HashMap<&'static str, &'static str> {
    let mut map = std::collections::HashMap::new();
    map.insert("frame_cible", " Global Configuration (AI Engine, Monitored Apps & Profiles) ");
    map.insert("tab_config", " ⚙ Global Configuration ");
    map.insert("tab_setup", " ⛭ Setup ");
    map.insert("tab_quickstart", " ❖ Help - Quick Start ");
    map.insert("tab_prompts", " ✎ Prompt Editor ");
    map.insert("tab_console", " ➤ Console & Monitor ");
    map.insert("frame_generateur", " ✨ AI Prompt Generator ");
    map.insert("frame_timeline", " 🌐 Action Visual Timeline (Git Commit-Style) ");
    map.insert("frame_logs", " 🔴 Real-time Activity Console & Logs ");
    map.insert("lbl_langue", "Language:");
    map.insert("lbl_profil", "Profile:");
    map.insert("lbl_selection_fenetres", "Target Windows:");
    map.insert("lbl_context", "0. General Situation Context:");
    map.insert("lbl_obj", "2. Stop Condition (Do While / Limits):");
    map.insert("lbl_tsk", "1. Global Task to Accomplish (Starting Instructions):");
    map.insert("lbl_dir", "3. Specific System Directives (AI Rules):");
    map.insert("lbl_moteur", "Engine:");
    map.insert("lbl_url", "API URL:");
    map.insert("lbl_modele", "Model:");
    map.insert("chk_son", "🔔 Sound notification");
    map.insert("chk_tooltips", "💬 Active tooltips");
    map.insert("btn_reinit", "🔄 Reset All");
    map.insert("btn_sauver", "💾 Save Profile");
    map.insert("btn_opti_court", "🪄 Optimize this field");
    map.insert("btn_clear_logs", "🗑️ Clear Logs");
    map.insert("btn_generer_tout", "✨ Generate Prompts");
    map.insert("btn_lancer", "🚀 Start");
    map.insert("btn_arreter", "⏹️ Stop");
    map.insert("btn_resume", "▶️ Resume");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_stop_demande", "⏹️ Stop requested by user.");
    map.insert("status_arrete", "⏹️ Stopped.");
    map.insert("btn_pause", "⏸️ PAUSE");
    map.insert("btn_reprendre", "▶️ RESUME AUTO");
    map.insert("btn_charger", "📂 Load");
    map.insert("btn_sauver_profil", "💾 Save");
    map.insert("btn_supprimer", "🗑️ Delete");
    map.insert("statut_pret", "Status: Ready");
    map.insert("statut_pause", "Status: Paused");
    map.insert("statut_reprise", "💾 A previous session was detected. Ready to resume!");
    map.insert("msg_reinit", "🔄 Everything has been reset to default!");
    map.insert("msg_sauve", "💾 Texts, language, and state saved!");
    map.insert("msg_vide", "⚠️ Please write your need or fill the selected field first!");
    map.insert("lbl_aucune_fenetre", "🖥️ All Screens (no target window specified)");
    map.insert("msg_opti_en_cours", "🪄 Qwen is optimizing the selected field...");
    map.insert("msg_opti_ok", "✅ Field optimized by AI!");
    map.insert("msg_gen_en_cours", "⚡ Building complete prompt configuration using AI...");
    map.insert("msg_gen_ok", "✅ All orchestration prompts successfully generated by AI!");
    map.insert("msg_confirm_titre", "Confirm Save");
    map.insert("msg_confirm_texte", "Warning: Do you really want to save and overwrite prompts and settings for profile '{}'?");
    map.insert("msg_confirm_texte_generique", "Warning: Do you want to save current prompts as the default profile (save.enc)?");
    map.insert("msg_nom_profil_titre", "New Profile");
    map.insert("msg_nom_profil_texte", "Enter the name of the new configuration profile:");
    map.insert("msg_nom_moteur_titre", "New AI Engine");
    map.insert("msg_nom_moteur_texte", "Enter the name of the new engine profile:");
    map.insert("msg_moteur_sauve", "✅ Engine profile saved!");
    map.insert("msg_moteur_supprime", "🗑️ Engine profile deleted!");
    map.insert("msg_confirm_supp_moteur_titre", "Confirm Deletion");
    map.insert("msg_confirm_supp_moteur_texte", "Are you sure you want to permanently delete engine '{}'?");
    map.insert("msg_confirm_gen_titre", "Confirm Global Generation");
    map.insert("msg_confirm_gen_texte", "Warning: Generation will overwrite all your current prompts. Do you want to continue?");
    map.insert("msg_profil_sauve", "✅ Profile saved successfully!");
    map.insert("msg_profil_charge", "📂 Profile loaded successfully!");
    map.insert("msg_profil_supprime", "🗑️ Profile deleted!");
    map.insert("msg_confirm_supp_titre", "Confirm Deletion");
    map.insert("msg_confirm_supp_texte", "Are you sure you want to permanently delete profile '{}'?");
    map.insert("btn_oui", "Yes");
    map.insert("btn_non", "Cancel");
    map.insert("legende_think", "T: Thinking");
    map.insert("legende_wait", "W: App Busy");
    map.insert("legende_cool", "CD: Stabilizing");
    map.insert("legende_scroll", "S: Scroll");
    map.insert("legende_click", "C: Type");
    map.insert("legende_success", "★: Success");
    map.insert("legende_fail", "X: Fail");
    map.insert("legende_sleep", "SL: Sleep/Lock");
    map.insert("legende_static", "ST: Static Screen");
    map.insert("log_screen_asleep", "⏳ Screen is asleep or locked. Waiting 5s...");
    map.insert("log_static_screen", "⏳ Static screen detected (no change). Waiting 10s...");
    map.insert("status_screen_asleep", "⏳ Screen asleep or locked...");
    map.insert("status_static_screen", "⏳ Static screen...");
    map.insert("all_screens", "ALL SCREENS (Virtual Desktop)");
    map.insert("screen_title", "Desktop - Screen {}");
    map.insert("frame_ia", " 1. AI Engine & Model (Vision LLM) ");
    map.insert("frame_windows", " 2. Monitored Target Applications ");
    map.insert("frame_profils", " 3. Profile Management ");
    map.insert("tip_frame_ia", "Configure the local or remote AI API provider and VLM model to analyze the screen.");
    map.insert("tip_frame_windows", "Select and manage the list of windows to watch. If empty, the entire screen is watched.");
    map.insert("tip_frame_profils", "Load, save, or delete complete sets of prompts and target window setups.");
    map.insert("tip_context", "Starting context to help the AI's vision (OS, tools, initial state).");
    map.insert("tip_tsk", "Main action instructions for the AI to interact with the interface (in technical English).");
    map.insert("tip_obj", "Final visually verifiable objective for the AI to know when to stop (in technical English).");
    map.insert("tip_dir", "Strict safety instructions and behavioral rules to guide the AI (in technical English).");
    map.insert("tip_refresh", "Refresh the active desktop window list");
    map.insert("tip_add_win", "Add the selected window to your watch list");
    map.insert("tip_del_win", "Remove selected window from your watch list");
    map.insert("tip_add_engine", "Add a new AI provider profile (LM Studio, Ollama...)");
    map.insert("tip_del_engine", "Delete currently selected AI provider profile");
    map.insert("tip_load_profile", "Load prompts and setup from this profile");
    map.insert("tip_save_profile", "Create a new profile or overwrite current");
    map.insert("tip_del_profile", "Permanently delete this profile from disk");
    map.insert("tip_optimize_field", "Ask local AI to reformulate this field in precise tech English");
    map.insert("tip_generate_all", "Ask AI to generate the complete orchestrator prompts based on your idea");
    map.insert("tip_clear_memory", "Delete resume/active work memory to start with a blank page");
    map.insert("log_fenetres_invisibles", "⏳ No monitored application is visible (minimized or closed). Waiting 5s...");
    map.insert("status_fenetres_invisibles", "⏳ Waiting for target windows...");
    map.insert("log_detection_occupe", "⏳ Detection {} : BUSY. Waiting...");
    map.insert("log_detection_libre", "⏳ Detection {} : FREE.");
    map.insert("log_fenetre_ajoutee", "➕ Window added to watch list: {}");
    map.insert("log_fenetre_retiree", "🗑️ Window removed from watch list: {}");
    map.insert("log_ia_adapte", "⚙️ AI parameters adapted for {}.");
    map.insert("log_moteur_enregistre", "💾 New AI engine profile saved: {}");
    map.insert("log_impossible_suppr_dernier", "⚠️ Cannot delete the last remaining engine.");
    map.insert("log_moteur_supprime", "🗑️ Engine profile deleted: {}");
    map.insert("log_profil_charge", "📂 Profile loaded: {}");
    map.insert("log_profil_supprime", "🗑️ Profile deleted: {}");
    map.insert("log_champ_optimise", "🪄 AI: Field '{}' optimized.");
    map.insert("log_gen_demandee", "⚡ Global auto-generation requested...");
    map.insert("log_gen_injectee", "⚡ Global configuration generated and injected.");
    map.insert("log_lancement_moteur", "🚀 Launching with engine: {} ({})");
    map.insert("log_pause", "⏸️ Automator paused.");
    map.insert("log_reprise", "▶️ Resuming automator.");
    map.insert("log_reflexion_ia", "🧠 [THINKING AI] Capture and sending for analysis by {}...");
    map.insert("log_succes", "★ Automation completed with SUCCESS!");
    map.insert("log_echec", "X Automation completed with FAILURE.");
    map.insert("log_attente_occupee", "⏳ [TASK WAIT] Target application is busy. Pause of {}s...");
    map.insert("log_lancement_visual", "📱 Launching VibePilot Visual Orchestrator.");
    map.insert("log_linux_detecte", "🐧 Linux OS detected.");
    map.insert("log_warning_wayland", "⚠️ [WARNING WAYLAND] Active Wayland session. Please use X11 for mouse clicks to work properly.");
    map.insert("log_x11_detecte", "✅ X11 display server detected. Ready for automation.");
    map.insert("log_sec_save", "[SECURITY] Configuration saved.");
    map.insert("log_error_opti", "❌ Error during optimization: {}");
    map.insert("msg_attente_inactivite", "⏳ Waiting for idle state ({}s)...");
    map.insert("status_reprise_init", "🔄 RESUMING...");
    map.insert("status_initialisation", "🚀 INITIALIZATION...");
    map.insert("status_reflexion", "🧠 [AI THINKING] {} is thinking...");
    map.insert("status_ia_decide", "🤖 AI: {}");
    map.insert("status_cooldown", "⏳ Cool-down ({}s)...");
    map.insert("status_waiting", "⏳ Waiting ({}s)...");
    map.insert("err_load_profile", "❌ Error loading profile: {}");
    map.insert("err_generic", "❌ Error: {}");
    map.insert("tip_clear_memory", "Delete resume/active work memory to start with a blank page");
    map.insert("log_memory_cleared", "Active work/resume memory cleared successfully.");
    map.insert("btn_resume", "Resume");
    map.insert("btn_clear_memory", "🧹 Reset");
    map.insert("log_reprise_existants", "💾 Resuming session: using existing prompts. To start a new goal, click 'Reset' first.");
    map.insert("chk_theme_sombre", "🌙 Dark Theme");
    map.insert("chk_auto_validate", "🔒 Auto-validate Standard Actions");
    map.insert("chk_auto_validate_dangerous", "🔒 Auto-validate Dangerous Commands");
    map.insert("tip_auto_validate", "If enabled, standard AI actions (like clicks and scrolls) are executed without manual confirmation.");
    map.insert("tip_auto_validate_dangerous", "If enabled, potentially dangerous terminal commands (e.g. rm, format, sudo) are automatically validated.");
    map.insert("tip_zoom_facteur", "Sets the zoom/scaling level of the interface. Forcing a fixed value (e.g. 100% or 125%) fixes infinite resizing loop bugs on Windows when dragging between screens with different DPI resolutions.");
    map.insert("security_warning_titre", "⚠️ AI Actions");
    map.insert("security_warning_texte", "The AI has decided the following actions:\n\n{actions}\n\nDo you want to execute them?");
    map.insert("security_warning_yes", "✅ Execute");
    map.insert("security_warning_no", "❌ Cancel");
    map.insert("btn_add_engine", "➕");
    map.insert("btn_del_engine", "🗑️");
    map.insert("btn_add_window", "➕");
    map.insert("btn_refresh_windows", "🔄");
    map.insert("lbl_auth_mode", "Authentication:");
    map.insert("lbl_api_key", "API Key:");
    map.insert("lbl_auth_login", "Username:");
    map.insert("lbl_auth_password", "Password:");
    map.insert("lbl_request_timeout", "Request Timeout (sec):");
    map.insert("lbl_auth_none", "None");
    map.insert("lbl_auth_api_key", "API Key");
    map.insert("lbl_auth_basic", "Basic Auth");
    map.insert("lbl_profile_ready", "Profile Created!");
    map.insert("msg_profile_ready", "The prompts are generated and the profile '{}' is ready.");
    map.insert("chk_verify_cursor", "🔍 Verify cursor placement before click or write");
    map.insert("chk_detect_activity", "⏸ Auto-pause on user activity (mouse/keyboard)");
    map.insert("status_user_active", "User active - Waiting...");
    map
}

// --- AI Prompts ---
pub const PROMPT_OPTIMIZE_CONTEXT: &str =
    "You are an expert Prompt Engineer. Take the raw situation context description and rewrite it into a clean, concise, precise description of the system, tools, and layout in English.\n\
     Return ONLY the final optimized text in crisp English without markdown or quotes.";

pub const PROMPT_OPTIMIZE_OBJECTIF: &str =
    "You are an expert Prompt Engineer. Take the user's raw goal/stop condition and rewrite it into a single, clean, precise logical sentence in English.\n\
     It must describe a clear, visually verifiable end-state.\n\
     Return ONLY the final optimized sentence in crisp English without markdown or quotes.";

pub const PROMPT_OPTIMIZE_TASK: &str =
    "You are an expert Prompt Engineer. Take the raw intention of the user and rewrite it into clean, precise, operational directives in English.\n\
     State clearly that the AI is the PC operator piloting the workspace interface.\n\
     Return ONLY the final optimized prompt in crisp English without markdown.";

pub const PROMPT_OPTIMIZE_DIRECTIVES: &str =
    "You are an expert Prompt Engineer. Take the raw operational rules and rewrite them into a structured, clear list of conditional rules (bullet points) in English for a Vision LLM to follow on screen.\n\
     Keep them highly operational. Return ONLY the final optimized bullet list in English without markdown.";

pub const PROMPT_OPTIMIZE_FEEDBACK: &str =
    "You are an expert Prompt Engineer. Take the user's raw operational feedback, correction, or hint for an automation task and rewrite it into a clear, concise, highly precise instruction in English for a Vision LLM to execute.\n\
     Keep it short and extremely actionable. Return ONLY the final optimized text in crisp English without markdown or quotes.";

pub const PROMPT_GLOBAL_GENERATION: &str =
    "You are an expert AI Architect and Prompt Engineer.\n\
     Your role is to translate a simple user request into a complete, structured configuration for a visual AI automation agent (Qwen-VL).\n\n\
     Given the user request, you must output a strict JSON object with EXACTLY four fields:\n\
     1. \"contexte\": A clear, concise description in English of the operating environment, OS, active tools, and initial setup state.\n\
     2. \"objectif\": A precise, visually verifiable logical condition in English representing the final success state.\n\
     3. \"task\": A clear, high-level directive in English explaining to the AI how to pilot the target application's interface to accomplish the goal.\n\
     4. \"directives\": A structured, clear bulleted list in English detailing the specific conditional system rules. You MUST NOT leave this field empty. If no specific directives are obvious, generate 3-4 default helpful operational rules (e.g. regarding waiting for app load, scrolling on overflow, or verifying actions).\n\n\
     You MUST respond ONLY with the raw JSON object (enclosed in { and }). No markdown block wrappers, no introduction, no explanation.";
